### ISSUE TITLE
An error occurred while running 'get_longest_isoform.py' 

### ISSUE THREAD

**Issue by MICHELLE-LMX** [Gaius-Augustus/TSEBRA#34]
Hi,
I ran 'get_longest_isoform.py' using the files under the TSEBRA/example/tsebra_workdir/ path and the following error occurred.

I used the following command: 
/TSEBRA/bin/get_longest_isoform.py -g braker1.gtf,braker2.gtf -o combined12.gtf

I got the following error:
### CHOOSE LONGEST ISOFORM FOR EACH GENE
Traceback (most recent call last):
  File "/TSEBRA/bin/get_longest_isoform.py", line 107, in <module>
    main()
  File "/TSEBRA/bin/get_longest_isoform.py", line 63, in main
    tx_longest = sorted([graph.__tx_from_key__(n) for \
  File "/TSEBRA/bin/get_longest_isoform.py", line 64, in <lambda>
    n in comp], key=lambda t:t.get_cds_len())[-1]
AttributeError: 'Transcript' object has no attribute 'get_cds_len'

Any suggestion on a solution?
Thanks,
Michelle

**Comment by GuitCos** [comment]
Hi, 

I ran into the same issue. Would be great to have a solution for picking up only the longest isoform for each gene out of TSEBRA, 
Thank you, 
Guillaume

**Comment by jmpolinski** [comment]
Any update on the cause/solution for this error message? I just got the same one

**Comment by LarsGab** [comment]
Hi, 

this has been fixed in commit b134a523481904c600a3b4f894cab7db937d5cb2 .
Best,
Lars

**Comment by sahoo-rk** [comment]
I execute the script with a single ```braker.gtf``` file and the error still persists in the updated version.

```
get_longest_isoform.py --gtf braker.gtf --out longiso.gtf

### READING GENE PREDICTION: [braker.gtf]
### BUILD OVERLAP GRAPH
### CHOOSE LONGEST ISOFORM FOR EACH GENE
Traceback (most recent call last):
  File "/home/sahoork/dumpack/TSEBRA/bin/get_longest_isoform.py", line 107, in <module>
    main()
  File "/home/sahoork/dumpack/TSEBRA/bin/get_longest_isoform.py", line 63, in main
    tx_longest = sorted([graph.__tx_from_key__(n) for \
  File "/home/sahoork/dumpack/TSEBRA/bin/get_longest_isoform.py", line 64, in <lambda>
    n in comp], key=lambda t:t.get_cds_len())[-1]
AttributeError: 'Transcript' object has no attribute 'get_cds_len'
```
Am I missing something? Please suggest.

Thanks,
